let data=null, selected=null, called=new Set();
const $=id=>document.getElementById(id);
async function scan(){const url=$('url').value.trim();if(!url)return;$('status').textContent='Opening game page and finding available tickets…';
try{const r=await fetch('/api/scan?url='+encodeURIComponent(url)+'&v=6');data=await r.json();if(!r.ok)throw Error(data.detail||'Scan failed');render(data);}catch(e){$('status').textContent=e.message}}
function render(d){$('status').textContent=`Detected: ${d.site} • ${d.tickets.length} ticket(s) found`;let h='<div class="card"><h2>Available tickets</h2><small>Tickets are read from the public game page. The bot does not predict future winning numbers.</small>';
if(!d.tickets.length){h+='<p>No readable tickets were returned yet. The site may need another ticket-page interaction or may protect its ticket data.</p>'}
d.tickets.forEach((t,i)=>{h+=`<div class="ticket ${i===d.selected_index?'best':''}"><b>${t.label||('Ticket '+(i+1))}</b> <small>score ${t.score} • ${t.source||'scan'}</small><div class="grid">${(t.flat||[]).map(n=>`<div class="cell">${n}</div>`).join('')}</div>${i===d.selected_index?'<p>⭐ Selected automatically</p>':''}</div>`});
h+='</div>'; $('result').innerHTML=h; selected=d.tickets[d.selected_index]; if(selected){$('tracker').classList.remove('hidden');$('ticketName').textContent=selected.label||'Selected ticket is locked for tracking.';draw();poll();}}
function draw(){if(!selected)return;const values=selected.flat||[];$('grid').innerHTML='<div class="grid">'+values.map(n=>`<div class="cell ${called.has(n)?'called':''}">${n}</div>`).join('')+'</div>';let hit=values.filter(n=>called.has(n)).length;$('progress').textContent=`${hit}/${values.length} ticket numbers called`;$('called').innerHTML=[...called].sort((a,b)=>a-b).map(n=>`<span class="pill">${n}</span>`).join('');if(hit===15)$('progress').textContent+=' • FULL HOUSE reached';}
async function poll(){if(!data||!selected)return;try{const r=await fetch('/api/called?url='+encodeURIComponent(data.url));if(r.ok){const d=await r.json();(d.called||[]).forEach(n=>called.add(Number(n)));draw();}}catch{}setTimeout(poll,3000)}
